### ISSUE TITLE
Change UI/UX for cart page

### ISSUE THREAD

**Issue by jeanyeeee** [jeanyeeee/dining-rc-app#6]
Under the `AuthForumScreen.js`
- [ ] Cart logo change to a write instead
- [ ] "Create new Review" make it into a bottom button `onPress = {() => navigation.navigate('NewReview')}`
- [ ] Display the meals same format as home page <GetForumReview navigation={navigation}/>

**Comment by jeanyeeee** [comment]
[Unhandled promise rejection: FirebaseError: Firebase Storage: The operation 'getDownloadURL' cannot be performed on a root reference, create a non-root reference using child, such as .child('file.png'). (storage/invalid-root-operation)]
at http://192.168.1.30:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:178962:321 in _createSuperInternal
at node_modules/@firebase/util/dist/index.esm2017.js:791:8 in FirebaseError#constructor
at http://192.168.1.30:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:184927:321 in _createSuperInternal
at node_modules/@firebase/storage/dist/index.esm2017.js:72:8 in StorageError#constructor
at node_modules/@firebase/storage/dist/index.esm2017.js:174:11 in invalidRootOperation
at node_modules/@firebase/storage/dist/index.esm2017.js:2757:38 in Reference#_throwIfRoot
at node_modules/@firebase/storage/dist/index.esm2017.js:2956:4 in getDownloadURL$1
at node_modules/@firebase/storage/dist/index.esm2017.js:3412:27 in getDownloadURL
at node_modules/react/cjs/react.development.js:365:2 in Component.prototype.setState
at node_modules/react-native/Libraries/Lists/VirtualizedList.js:1735:4 in _updateCellsToRender
at node_modules/react-native/Libraries/Interaction/Batchinator.js:69:8 in InteractionManager.runAfterInteractions$argument_0
at node_modules/react-native/Libraries/Interaction/TaskQueue.js:115:14 in processNext
at node_modules/react-native/Libraries/Interaction/InteractionManager.js:207:6 in _processUpdate

**Comment by jeanyeeee** [comment]
- [ ] Need to retrieve data from the dining food database
